[package]
name = "kernel"
version = "0.1.0"
edition = "2018"

[dependencies]
x86_64 = "0.15.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "kernel"
path = "src/main.rs"