[build]
target = "x86_64-unknown-none.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(target_os = "none")']
rustflags = ["-C", "link-arg=--script=./linker.ld", "-C", "link-arg=--verbose"]